
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label8;

	private global::Gtk.Entry txtHostname;

	private global::Gtk.Button button8;

	private global::Gtk.Button button10;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.Notebook notebook3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Label label26;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview2;

	private global::Gtk.Label label27;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.NodeView nodeview3;

	private global::Gtk.Table table1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button9;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.TextView textview4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview3;

	private global::Gtk.Label label18;

	private global::Gtk.Label label19;

	private global::Gtk.Label label16;

	private global::Gtk.Label label20;

	private global::Gtk.Label label21;

	private global::Gtk.Label label22;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.NodeView nodeview4;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox7;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.CheckButton checkbutton2;

	private global::Gtk.CheckButton checkbutton3;

	private global::Gtk.CheckButton checkbutton8;

	private global::Gtk.CheckButton checkbutton7;

	private global::Gtk.CheckButton checkbutton6;

	private global::Gtk.CheckButton checkbutton5;

	private global::Gtk.CheckButton checkbutton4;

	private global::Gtk.Label label23;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Label label11;

	private global::Gtk.Image image3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label9;

	private global::Gtk.Image image4;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label3;

	private global::Gtk.Image image5;

	private global::Gtk.VBox vbox12;

	private global::Gtk.Label label14;

	private global::Gtk.Image image8;

	private global::Gtk.VBox vbox11;

	private global::Gtk.Label label13;

	private global::Gtk.Image image7;

	private global::Gtk.VBox vbox10;

	private global::Gtk.Label label12;

	private global::Gtk.Image image6;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Label label29;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.Table table3;

	private global::Gtk.Button button11;

	private global::Gtk.Button button12;

	private global::Gtk.Button button13;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button7;

	private global::Gtk.Notebook notebook2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.TextView txtVertexes;

	private global::Gtk.DrawingArea daVertexes;

	private global::Gtk.Label label10;

	private global::Gtk.ScrolledWindow GtkScrolledWindow8;

	private global::Gtk.TextView txtIspTsp;

	private global::Gtk.Label label6;

	private global::Gtk.HBox hbox6;

	private global::Gtk.TextView txtTcw;

	private global::Gtk.ScrolledWindow GtkScrolledWindow6;

	private global::Gtk.Image imgTcw;

	private global::Gtk.Label label5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow7;

	private global::Gtk.TextView textview6;

	private global::Gtk.Label label4;

	private global::Gtk.Label label1;

	private global::Gtk.Label label7;

	private global::Gtk.Label label17;

	private global::Gtk.Label label24;

	private global::Gtk.Label label25;

	private global::Gtk.Label label28;

	private global::Gtk.Button button1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("ReiDBG");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Reicast Host");
		this.hbox3.Add(this.label8);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label8]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtHostname = new global::Gtk.Entry();
		this.txtHostname.CanFocus = true;
		this.txtHostname.Name = "txtHostname";
		this.txtHostname.Text = global::Mono.Unix.Catalog.GetString("localhost:8828");
		this.txtHostname.IsEditable = true;
		this.txtHostname.InvisibleChar = '•';
		this.hbox3.Add(this.txtHostname);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtHostname]));
		w2.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox3.Add(this.button8);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button8]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button();
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("Disconnect");
		this.hbox3.Add(this.button10);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button10]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 3;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.notebook3 = new global::Gtk.Notebook();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label26 = new global::Gtk.Label();
		this.label26.Name = "label26";
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Instruction Stream");
		this.vbox6.Add(this.label26);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label26]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview2 = new global::Gtk.NodeView();
		this.nodeview2.CanFocus = true;
		this.nodeview2.Name = "nodeview2";
		this.GtkScrolledWindow.Add(this.nodeview2);
		this.vbox6.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
		w8.Position = 1;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Call Stack");
		this.vbox6.Add(this.label27);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label27]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow3.Add(this.nodeview3);
		this.vbox6.Add(this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow3]));
		w11.Position = 3;
		// Container child vbox6.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Run");
		this.table1.Add(this.button2);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.button2]));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Pause");
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Step");
		this.table1.Add(this.button6);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.button6]));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Skip");
		this.table1.Add(this.button9);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox6.Add(this.table1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.table1]));
		w16.Position = 4;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox2.Add(this.vbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.textview4 = new global::Gtk.TextView();
		this.textview4.Buffer.Text = global::Mono.Unix.Catalog.GetString("Main Registers");
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.GtkScrolledWindow4.Add(this.textview4);
		this.hbox2.Add(this.GtkScrolledWindow4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow4]));
		w19.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView();
		this.textview3.Buffer.Text = global::Mono.Unix.Catalog.GetString("FPU Registers");
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow2.Add(this.textview3);
		this.hbox2.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow2]));
		w21.Position = 2;
		this.notebook3.Add(this.hbox2);
		// Notebook tab
		this.label18 = new global::Gtk.Label();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Debugger");
		this.notebook3.SetTabLabel(this.hbox2, this.label18);
		this.label18.ShowAll();
		// Notebook tab
		global::Gtk.Label w23 = new global::Gtk.Label();
		w23.Visible = true;
		this.notebook3.Add(w23);
		this.label19 = new global::Gtk.Label();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("INTC");
		this.notebook3.SetTabLabel(w23, this.label19);
		this.label19.ShowAll();
		// Notebook tab
		global::Gtk.Label w24 = new global::Gtk.Label();
		w24.Visible = true;
		this.notebook3.Add(w24);
		this.label16 = new global::Gtk.Label();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("DMAC");
		this.notebook3.SetTabLabel(w24, this.label16);
		this.label16.ShowAll();
		// Notebook tab
		global::Gtk.Label w25 = new global::Gtk.Label();
		w25.Visible = true;
		this.notebook3.Add(w25);
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("SCIF");
		this.notebook3.SetTabLabel(w25, this.label20);
		this.label20.ShowAll();
		// Notebook tab
		global::Gtk.Label w26 = new global::Gtk.Label();
		w26.Visible = true;
		this.notebook3.Add(w26);
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Other Peripherals");
		this.notebook3.SetTabLabel(w26, this.label21);
		this.label21.ShowAll();
		this.notebook1.Add(this.notebook3);
		// Notebook tab
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("MCPU: SH4");
		this.notebook1.SetTabLabel(this.notebook3, this.label22);
		this.label22.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.nodeview4 = new global::Gtk.NodeView();
		this.nodeview4.CanFocus = true;
		this.nodeview4.Name = "nodeview4";
		this.GtkScrolledWindow5.Add(this.nodeview4);
		this.notebook1.Add(this.GtkScrolledWindow5);
		global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow5]));
		w29.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("MCPU: Memory");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow5, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("MCPU: CH0");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.hbox7.Add(this.checkbutton1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton1]));
		w30.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString("MCPU: CH1");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.hbox7.Add(this.checkbutton2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton2]));
		w31.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton3 = new global::Gtk.CheckButton();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("MCPU: CH2");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.hbox7.Add(this.checkbutton3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton3]));
		w32.Position = 2;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton8 = new global::Gtk.CheckButton();
		this.checkbutton8.CanFocus = true;
		this.checkbutton8.Name = "checkbutton8";
		this.checkbutton8.Label = global::Mono.Unix.Catalog.GetString("SB: SortDMA");
		this.checkbutton8.DrawIndicator = true;
		this.checkbutton8.UseUnderline = true;
		this.hbox7.Add(this.checkbutton8);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton8]));
		w33.PackType = ((global::Gtk.PackType)(1));
		w33.Position = 3;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton7 = new global::Gtk.CheckButton();
		this.checkbutton7.CanFocus = true;
		this.checkbutton7.Name = "checkbutton7";
		this.checkbutton7.Label = global::Mono.Unix.Catalog.GetString("SB: Maple");
		this.checkbutton7.DrawIndicator = true;
		this.checkbutton7.UseUnderline = true;
		this.hbox7.Add(this.checkbutton7);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton7]));
		w34.PackType = ((global::Gtk.PackType)(1));
		w34.Position = 4;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton6 = new global::Gtk.CheckButton();
		this.checkbutton6.CanFocus = true;
		this.checkbutton6.Name = "checkbutton6";
		this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("SB: GDROM");
		this.checkbutton6.DrawIndicator = true;
		this.checkbutton6.UseUnderline = true;
		this.hbox7.Add(this.checkbutton6);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton6]));
		w35.PackType = ((global::Gtk.PackType)(1));
		w35.Position = 5;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton5 = new global::Gtk.CheckButton();
		this.checkbutton5.CanFocus = true;
		this.checkbutton5.Name = "checkbutton5";
		this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("SB: AICA");
		this.checkbutton5.DrawIndicator = true;
		this.checkbutton5.UseUnderline = true;
		this.hbox7.Add(this.checkbutton5);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton5]));
		w36.PackType = ((global::Gtk.PackType)(1));
		w36.Position = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.checkbutton4 = new global::Gtk.CheckButton();
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString("MCPU: CH3");
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.hbox7.Add(this.checkbutton4);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.checkbutton4]));
		w37.PackType = ((global::Gtk.PackType)(1));
		w37.Position = 7;
		this.vbox7.Add(this.hbox7);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		this.notebook1.Add(this.vbox7);
		global::Gtk.Notebook.NotebookChild w39 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox7]));
		w39.Position = 2;
		// Notebook tab
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("DMAs");
		this.notebook1.SetTabLabel(this.vbox7, this.label23);
		this.label23.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Params");
		this.vbox9.Add(this.label11);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label11]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.image3 = new global::Gtk.Image();
		this.image3.WidthRequest = 64;
		this.image3.HeightRequest = 64;
		this.image3.Name = "image3";
		this.vbox9.Add(this.image3);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.image3]));
		w41.Position = 1;
		w41.Expand = false;
		w41.Fill = false;
		this.hbox1.Add(this.vbox9);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox9]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Depth 1");
		this.vbox4.Add(this.label9);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label9]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image();
		this.image4.WidthRequest = 64;
		this.image4.HeightRequest = 64;
		this.image4.Name = "image4";
		this.vbox4.Add(this.image4);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image4]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		this.hbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Depth 2");
		this.vbox3.Add(this.label3);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.image5 = new global::Gtk.Image();
		this.image5.WidthRequest = 64;
		this.image5.HeightRequest = 64;
		this.image5.Name = "image5";
		this.vbox3.Add(this.image5);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image5]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Accum2");
		this.vbox12.Add(this.label14);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label14]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.image8 = new global::Gtk.Image();
		this.image8.WidthRequest = 64;
		this.image8.HeightRequest = 64;
		this.image8.Name = "image8";
		this.vbox12.Add(this.image8);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.image8]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		this.hbox1.Add(this.vbox12);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox12]));
		w51.PackType = ((global::Gtk.PackType)(1));
		w51.Position = 3;
		w51.Expand = false;
		w51.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Accum 1");
		this.vbox11.Add(this.label13);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label13]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.image7 = new global::Gtk.Image();
		this.image7.WidthRequest = 64;
		this.image7.HeightRequest = 64;
		this.image7.Name = "image7";
		this.vbox11.Add(this.image7);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.image7]));
		w53.Position = 1;
		w53.Expand = false;
		w53.Fill = false;
		this.hbox1.Add(this.vbox11);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox11]));
		w54.PackType = ((global::Gtk.PackType)(1));
		w54.Position = 4;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Stencil");
		this.vbox10.Add(this.label12);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label12]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.image6 = new global::Gtk.Image();
		this.image6.WidthRequest = 64;
		this.image6.HeightRequest = 64;
		this.image6.Name = "image6";
		this.vbox10.Add(this.image6);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.image6]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		this.hbox1.Add(this.vbox10);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox10]));
		w57.PackType = ((global::Gtk.PackType)(1));
		w57.Position = 5;
		w57.Expand = false;
		w57.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.label29 = new global::Gtk.Label();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Command Stream");
		this.vbox8.Add(this.label29);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label29]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.WidthRequest = 300;
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow1.Add(this.nodeview1);
		this.vbox8.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow1]));
		w61.Position = 1;
		// Container child vbox8.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.table3.Add(this.button11);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table3[this.button11]));
		w62.TopAttach = ((uint)(1));
		w62.BottomAttach = ((uint)(2));
		w62.LeftAttach = ((uint)(2));
		w62.RightAttach = ((uint)(3));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button12 = new global::Gtk.Button();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString("Step Tile");
		this.table3.Add(this.button12);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table3[this.button12]));
		w63.TopAttach = ((uint)(1));
		w63.BottomAttach = ((uint)(2));
		w63.LeftAttach = ((uint)(1));
		w63.RightAttach = ((uint)(2));
		w63.XOptions = ((global::Gtk.AttachOptions)(4));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("Step Frame");
		this.table3.Add(this.button13);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table3[this.button13]));
		w64.TopAttach = ((uint)(1));
		w64.BottomAttach = ((uint)(2));
		w64.XOptions = ((global::Gtk.AttachOptions)(4));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Disable");
		this.table3.Add(this.button3);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table3[this.button3]));
		w65.LeftAttach = ((uint)(1));
		w65.RightAttach = ((uint)(2));
		w65.XOptions = ((global::Gtk.AttachOptions)(4));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Step");
		this.table3.Add(this.button4);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table3[this.button4]));
		w66.LeftAttach = ((uint)(2));
		w66.RightAttach = ((uint)(3));
		w66.XOptions = ((global::Gtk.AttachOptions)(4));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Enable");
		this.table3.Add(this.button7);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table3[this.button7]));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox8.Add(this.table3);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.table3]));
		w68.Position = 2;
		w68.Expand = false;
		w68.Fill = false;
		this.hbox4.Add(this.vbox8);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox8]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 2;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.txtVertexes = new global::Gtk.TextView();
		this.txtVertexes.HeightRequest = 96;
		this.txtVertexes.CanFocus = true;
		this.txtVertexes.Name = "txtVertexes";
		this.txtVertexes.Editable = false;
		this.vbox5.Add(this.txtVertexes);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtVertexes]));
		w70.Position = 0;
		w70.Expand = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.daVertexes = new global::Gtk.DrawingArea();
		this.daVertexes.Name = "daVertexes";
		this.vbox5.Add(this.daVertexes);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.daVertexes]));
		w71.Position = 1;
		this.notebook2.Add(this.vbox5);
		// Notebook tab
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Vertexes");
		this.notebook2.SetTabLabel(this.vbox5, this.label10);
		this.label10.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow8 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow8.Name = "GtkScrolledWindow8";
		this.GtkScrolledWindow8.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow8.Gtk.Container+ContainerChild
		this.txtIspTsp = new global::Gtk.TextView();
		this.txtIspTsp.CanFocus = true;
		this.txtIspTsp.Name = "txtIspTsp";
		this.txtIspTsp.Editable = false;
		this.GtkScrolledWindow8.Add(this.txtIspTsp);
		this.notebook2.Add(this.GtkScrolledWindow8);
		global::Gtk.Notebook.NotebookChild w74 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow8]));
		w74.Position = 1;
		// Notebook tab
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("ISP/TSP Setup");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow8, this.label6);
		this.label6.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.txtTcw = new global::Gtk.TextView();
		this.txtTcw.WidthRequest = 128;
		this.txtTcw.CanFocus = true;
		this.txtTcw.Name = "txtTcw";
		this.txtTcw.Editable = false;
		this.hbox6.Add(this.txtTcw);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.txtTcw]));
		w75.Position = 0;
		w75.Expand = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
		this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
		global::Gtk.Viewport w76 = new global::Gtk.Viewport();
		w76.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.imgTcw = new global::Gtk.Image();
		this.imgTcw.Name = "imgTcw";
		w76.Add(this.imgTcw);
		this.GtkScrolledWindow6.Add(w76);
		this.hbox6.Add(this.GtkScrolledWindow6);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.GtkScrolledWindow6]));
		w79.Position = 1;
		this.notebook2.Add(this.hbox6);
		global::Gtk.Notebook.NotebookChild w80 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.hbox6]));
		w80.Position = 2;
		// Notebook tab
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("TCW Setup");
		this.notebook2.SetTabLabel(this.hbox6, this.label5);
		this.label5.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
		this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
		this.textview6 = new global::Gtk.TextView();
		this.textview6.CanFocus = true;
		this.textview6.Name = "textview6";
		this.textview6.Editable = false;
		this.GtkScrolledWindow7.Add(this.textview6);
		this.notebook2.Add(this.GtkScrolledWindow7);
		global::Gtk.Notebook.NotebookChild w82 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow7]));
		w82.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Fpu Entry");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow7, this.label4);
		this.label4.ShowAll();
		this.hbox4.Add(this.notebook2);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.notebook2]));
		w83.Position = 1;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w84.Position = 1;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w85 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w85.Position = 3;
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("CLX2: CORE");
		this.notebook1.SetTabLabel(this.vbox2, this.label1);
		this.label1.ShowAll();
		// Notebook tab
		global::Gtk.Label w86 = new global::Gtk.Label();
		w86.Visible = true;
		this.notebook1.Add(w86);
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("CLX2: TA");
		this.notebook1.SetTabLabel(w86, this.label7);
		this.label7.ShowAll();
		// Notebook tab
		global::Gtk.Label w87 = new global::Gtk.Label();
		w87.Visible = true;
		this.notebook1.Add(w87);
		this.label17 = new global::Gtk.Label();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("SPG/DVE");
		this.notebook1.SetTabLabel(w87, this.label17);
		this.label17.ShowAll();
		// Notebook tab
		global::Gtk.Label w88 = new global::Gtk.Label();
		w88.Visible = true;
		this.notebook1.Add(w88);
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("SCPU: ARM7DI");
		this.notebook1.SetTabLabel(w88, this.label24);
		this.label24.ShowAll();
		// Notebook tab
		global::Gtk.Label w89 = new global::Gtk.Label();
		w89.Visible = true;
		this.notebook1.Add(w89);
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("AICA");
		this.notebook1.SetTabLabel(w89, this.label25);
		this.label25.ShowAll();
		// Notebook tab
		global::Gtk.Label w90 = new global::Gtk.Label();
		w90.Visible = true;
		this.notebook1.Add(w90);
		this.label28 = new global::Gtk.Label();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("DSP");
		this.notebook1.SetTabLabel(w90, this.label28);
		this.label28.ShowAll();
		this.vbox1.Add(this.notebook1);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w91.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Quit");
		this.vbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button1]));
		w92.Position = 2;
		w92.Expand = false;
		w92.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1101;
		this.DefaultHeight = 718;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.Window_OnDelete);
		this.button8.Clicked += new global::System.EventHandler(this.Connect);
		this.button10.Clicked += new global::System.EventHandler(this.Disconnect);
		this.button7.Clicked += new global::System.EventHandler(this.EnableCoreDebugging);
		this.button4.Clicked += new global::System.EventHandler(this.CoreOnStep);
		this.button3.Clicked += new global::System.EventHandler(this.DisableCoreDebugging);
		this.button13.Clicked += new global::System.EventHandler(this.CoreNextFrame);
		this.button12.Clicked += new global::System.EventHandler(this.CoreNextTile);
		this.button11.Clicked += new global::System.EventHandler(this.CoreClearList);
		this.daVertexes.ExposeEvent += new global::Gtk.ExposeEventHandler(this.daVertexes_OnDraw);
	}
}
