version: git-{branch}-{build}
image: Visual Studio 2017

configuration:
- RelWithDebInfo

platform:
- x64

before_build:
  - cmd: >-
      if "%CONFIGURATION%"=="RelWithDebInfo" (set BUILD_PATH=build)
      
      if not exist %BUILD_PATH% (mkdir %BUILD_PATH%)
     
      if "%CONFIGURATION%"=="RelWithDebInfo" (cmake -B %BUILD_PATH% -G "Visual Studio 15 2017 Win64" -DCMAKE_CONFIGURATION_TYPES=RelWithDebInfo)
      
      cd %BUILD_PATH%
      
build_script:
  - cmd: >-
      if "%CONFIGURATION%"=="RelWithDebInfo" (msbuild reicast.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll")
      

after_build:
  - cmd: >-      
      if "%CONFIGURATION%"=="RelWithDebInfo" (cd .. && set EXE_PATH=build\RelWithDebInfo\reicast.exe)
      
      mkdir artifacts
      
      move %EXE_PATH% artifacts\reicast-win_%PLATFORM%-%CONFIGURATION%-%APPVEYOR_REPO_COMMIT%.exe
      
artifacts:
  - path: artifacts
    name: reicast-win_$(PLATFORM)-$(CONFIGURATION)-$(APPVEYOR_REPO_COMMIT)

deploy:
- provider: S3
  access_key_id: AKIAJETEBUZSLZF3YNKA
  secret_access_key:
    secure: ZxrysCeqMK99dOOzKyoeN4R5aO8JjA4RTrwVAQPQHz8sjyyKuVDZT2fC+9m6lUIi
  region: eu-west-1
  bucket: reicast-builds-windows
  folder: 'builds/heads/$(APPVEYOR_REPO_BRANCH)-$(APPVEYOR_REPO_COMMIT)'
  artifact: reicast-win_$(PLATFORM)-$(CONFIGURATION)-$(APPVEYOR_REPO_COMMIT)
  set_public: true
